config/routes.rb
OnlineBlog::Application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :posts
  get 'categorized' => 'posts#categorized', via: :get    
  get 'tagged' => 'posts#tagged', via: :get      
  resources :comments, only: [:create, :destroy]
  root 'static_pages#home'
  get "about" => 'static_pages#about'  

  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, class_name: "Category", foreign_key: "parent_id"
  belongs_to :parent_category, class_name: "Category"
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post 
  belongs_to :user

  validates :comment_text, presence: true, length: { maximum: 512 }
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  validates :title, presence: true  
  validates :content, presence: true
  validates :user, presence: true
  searchable do
    text :title
    text :content, stored: true

    time :created_at
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :send_signup_notification
  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :destroy 

  def admin?
    self == User.first
  end

  private

    def send_signup_notification
      UserMailer.signup_notification(self).deliver
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create  
    @post = Post.find(params[:comment][:post_id])
    @comment = @post.comments.build(comment_params)

    unless user_signed_in?
      @comment.valid?
      if verify_recaptcha() && @comment.save
        flash[:success] = 'Comment added!'  
      else
        flash.now[:error] = "Enter coorect captcha text"
      end
    else 
      if @comment.save      
        flash[:success] = 'Comment added!'      
      else
        flash.now[:error] = "Error adding comment: #{@comment.errors}"
      end
    end  
    redirect_to @post
  end

  def destroy
    Comment.find(params[:id]).destroy    
    redirect_to @comment.post
  end

  private
    def comment_params
      params.require(:comment).permit(:comment_text, :user_id, :post_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :destroy, :create, :edit, :update]
  before_action :define_user
 
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Post created!'
      redirect_to user_path(@user)
    else
      @posts = []
      render 'new'      
    end    
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted."
    redirect_to :back    
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new(user_id: @user.id)
  end

  def show
    @post = Post.find(params[:id])    
    @comment = Comment.new(post: @post, user: @user)
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)     
      flash[:succes] = "Post updated"
      redirect_to @post.user
    else
      render 'edit'
    end    
  end


  def categorized
    if params[:category].present?
      #@posts = Post.find_by_category_id(params[:category]).paginate(page: params[:page], per_page: 5)
      @posts = Post.all.where("category_id = #{params[:category].to_i}").paginate(page: params[:page], per_page: 5)
    else      
      @posts = nil
    end
    @filter = "category: " + Category.find(params[:category]).name
  end

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 5)
    else      
      @posts = nil
    end
    @filter = "tag: " + params[:tag]
  end

  private
  
    def define_user
      @user = current_user
    end

    def post_params
      params.require(:post).permit(:title, :content, :category_id, :tag_list)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user    
    @search = Post.search do 
      fulltext params[:search] do
        highlight :content
      end

      #if params[:q].present?
       # keywords(params[:q]) do
        #  highlight :content
       # end      
      #end
      order_by :created_at, :desc
      paginate(page: params[:page], per_page: 5)
    end
    @posts = @search.results
    #@posts = Post.order("created_at desc").paginate(page: params[:page], per_page: 5)    
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_id(params[:id])    
    @posts = @user.posts.order('created_at desc').paginate(page: params[:page], per_page: 5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_page_title(page_title)
    application_title = 'Online Blog'
    if page_title.empty?
      application_title
    else
      application_title + " | " + page_title
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_image(user, options = { size: 64 } )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

end

app/views/layouts/application.slim
doctype html
html
  head
    title #{full_page_title(yield(:title))}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags 

  body
    header class="navbar navbar-fixed-top navbar-inverse" role="navigation"
      div class="navbar-inner" 
        div class="container" 
          = link_to "Online Blog", root_path, id: "logo"
          nav
            ul class="nav nav-pills pull-right"
              li = link_to "Home", root_path
              - if user_signed_in?
                li = link_to "Profile", user_path(current_user)             
                li = link_to "Settings", edit_user_registration_path
                li = link_to "Logout", destroy_user_session_path, method: :delete
              - else
                li = link_to "Sign up", new_user_registration_path
                li = link_to "Login", new_user_session_path
    div class="container"
      = yield 

app/views/posts/_comment.slim
section class="comment"
  h5 #{comment.user.nil? ? "Visitor" : comment.user.name}  commented #{time_ago_in_words(comment.created_at)} ago:
  
  h6
    = comment.comment_text + " " 
    = link_to "delete", comment, method: :delete, 
        data: { confirm: "Are you sure?" }, class: "post-sublinks" if (current_user == comment.user && user_signed_in?) ||current_user.admin? 

app/views/posts/_post.slim
li
  h3 = link_to post.title, post, class: "title"
  p class="post-content" 
    - unless post.content.length < 1024
      #{post.content[0..1020] + "..."}
    - else
      #{post.content} 
    i = pluralize(post.comments.count, "comment") unless post.comments.count == 0

  p class="timestamp"
    | Posted #{time_ago_in_words(post.created_at)} ago.   
    - if current_user == post.user
      span = link_to "edit", edit_post_path(post.id), class: "post-sublinks"
      span #{' | '}     
      span = link_to "delete", post, method: :delete, 
              data: { confirm: "Are you sure?" }, title: post.title, 
              class: "post-sublinks"

app/views/posts/categorized.slim
= render 'shared/filtered_posts'

app/views/posts/edit.slim
div class="row"
  aside class="span4"
    section
      = render 'shared/user_info'       

    section 
      = render "shared/post_form"

app/views/posts/new.slim
div class="row"
  aside class="span4"
    section
      = render 'shared/user_info'   
    section
      = render 'shared/post_form'

app/views/posts/show.slim
div class="row"
  aside class="span4"
    - if user_signed_in?
      section
        = render 'shared/user_info' 

    section         
      h3
        = link_to(@post.title, @post, class: "title") 

      p class="post-content"
        #{@post.content}
      aside
        div class="align-right"
          - if current_user == @post.user
            = link_to("edit", edit_post_path(@post.id), class: "post-sublinks") + " | "
            = link_to "delete", @post, method: :delete, 
              data: { confirm: "Are you sure?" }, title: @post.title, class: "post-sublinks"

        div class="align-left tags"
          - if !@post.category_id.nil?
            = "Category: "
            = link_to(@post.category.name, categorized_path(category: @post.category), class: "post-sublinks")

        div class="align-left tags"
          - @post.tags.any?
            = "Tags: "
            - @post.tags.each do |tag|
              = link_to(tag.name, tagged_path(tag: tag.name), class: "post-sublinks") + " "
    

    div class="row"
      aside class="comments"
        /p Comments
        = render partial: "comment", collection: @post.comments

      /- if user_signed_in?
      div class="new-comment"
        = form_for @comment do |f|        
          = f.hidden_field :post_id
          = f.hidden_field :user_id         
          p
            /= f.label :comment_text
            = f.text_area :comment_text

          - unless user_signed_in?  
            p
              = raw recaptcha_tags              

          p
            = f.submit "Add comment"

app/views/posts/tagged.slim
= render 'shared/filtered_posts'

app/views/shared/_error_messages.slim
- if object.errors.any?
  div id="error explanation"
    div class="alert alert-error"
      The form contains #{pluralize(object.errors.count, "error")}.
    ul
      - object.errors.full_messages.each do |msg|
        li * #{msg} 

app/views/shared/_feed.slim
= form_tag root_path, method: :get do
  section class="search-panel"
    = text_field_tag :search, params[:search]
    = submit_tag "Search", name: nil, id: "search-btn"

- unless @posts.empty? 
  div class="span8"
    ol class="posts"
      = render @posts
    = will_paginate @posts     

app/views/shared/_filtered_posts.slim
- unless @posts.nil?
  h1 Posts by #{@filter}

  div class="span8"
    ol class="posts"
      = render @posts
    = will_paginate @posts unless @posts.empty?     
- else
  h1 No posts found

app/views/shared/_post_form.slim
= form_for(@post) do |f|
  = render 'shared/error_messages', object: f.object
  
  div class="post_content"
    = f.label :title
    = f.text_field :title, id: "title_field"

    = f.label :content
    = f.text_area :content, placeholder: "Enter your post...", id: "content_field"

    = f.label :category_id
    = f.select :category_id, Category.all.collect { |c| [("  -  " if !c.parent_id.nil?).to_s + c.name, c.id] }  , include_blank: true, id: "select_field"

    = f.label :tags
    = f.text_field :tag_list

    = f.submit "Post", class:"btn btn-large btn-primary", id: "submit_button", 
      disabled: (@post.id == nil)
    - if request.env['PATH_INFO'] == edit_post_path(@post)
      = f.button "Cancel", class:"btn btn-large"      

javascript:
  $('#title_field, #content_field').keyup(function(){
    if ($('#content_field').val() != "" && $('#title_field').val() != "") 
    {     
      $('#submit_button').attr('disabled', false);      
    }
    else
    {
      $('#submit_button').attr('disabled', true);         
    }
  });

app/views/shared/_user_info.slim
= link_to gravatar_image(@user, size: 96), @user
h2
  #{@user.name}
span
  = link_to "view profile", @user, class: "post-sublinks"
span class="post-sublinks"
  = pluralize(@user.posts.count, "post")
p
- if user_signed_in? and current_user == @user
  = button_to "Add post", new_post_path, class: "btn btn-large btn-primary", method: :get   

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>

app/views/static_pages/about.slim
- provide(:title, 'About')
h1 About
#content
  p This is a test job application,
    an online blog,
    developed by Ramil Gilmanov.

app/views/static_pages/home.slim
- provide(:title, 'Home')
- if user_signed_in?
  div class="row"
    aside class="span4"
      section
        = render 'shared/user_info'
div
  = render 'shared/feed'

app/views/users/show.slim
- provide(:title, @user.name)
div class="row"
  aside class="span4"
    section
      = render 'shared/user_info'      

div class="span8"
  h3 Posts (#{@user.posts.count})
  = render 'shared/feed'
      